# ============================================================
# pg_hba.conf — STANDBY SERVER
# ============================================================

# TYPE  DATABASE        USER            ADDRESS                 METHOD

local   all             all                                     trust
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# Allow app to connect to standby for READ-ONLY queries
host    vaultlife_db    vaultlife_user  10.0.0.0/8              scram-sha-256

# ← ADD THIS LINE — allows TablePlus / pgAdmin from host machine
host    all             all             172.0.0.0/8             scram-sha-256

# Allow replication from primary (for cascading standby)
host    replication     all             0.0.0.0/0               scram-sha-256
host    replication     replicator      172.28.0.0/16           scram-sha-256